In [1]:
import sys




import os
from main.orchestrator import main
# --- Configuração da Execução ---
# Garante que o diretório raiz do projeto esteja no path
# para que 'src' possa ser encontrado.
# (Pode não ser necessário dependendo de como o VS Code lança o kernel,
# mas é uma boa prática para garantir a robustez)
if os.getcwd() not in sys.path:
    sys.path.insert(0, os.getcwd())
# Armazena os argumentos originais da linha de comando
original_argv = sys.argv
# Define os argumentos para esta execução específica
# O primeiro elemento é tradicionalmente o nome do script
sys.argv = [
    'src/run.py',
    '-d', '../data/beneficios-qualireg',
    '-p', 'discovery',
    '--output-format', 'interactive'
]
try:
    # Chama a função principal que agora irá
    # renderizar os resultados diretamente na sua janela
    main()
finally:
    # Restaura os argumentos originais (importante para
    # não afetar outras células do notebook)
    sys.argv = original_argv